server:
  port: 8092

logging:
  level:
    sql: debug

spring:
  datasource:
    druid:
      url: "jdbc:mysql://localhost:3306/p2p_account?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
      username: "root"
      password: "xxf123456"
      driver-class-name: com.mysql.cj.jdbc.Driver
      filter:
        stat:
          enabled: true
      initial-size: 1
      max-active: 20
      max-wait: 6000
      min-idle: 1
      time-between-eviction-runs-millis: 2000
      min-evictable-idle-time-millis: 600000
      max-evictable-idle-time-millis: 900000
      validation-query: "select 1"
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      keep-alive: true
      phy-max-use-count: 1000
  #nacos注册中心配置
  application:
    name: "user-service"
  cloud:
    nacos:
      discovery:
        server-addr: "192.168.10.13:8848"
management:
  endpoints:
    web:
      exposure:
        include: "*"
mybatis:
  type-aliases-package: com.sherfin.mapperBean
  type-handlers-package: com.sherfin.typehandler
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30

